DROP USER IF EXISTS 'lccdbuser'@'localhost';
DROP DATABASE IF EXISTS LCC;
CREATE DATABASE LCC;
CREATE USER 'lccdbuser'@'localhost' IDENTIFIED BY 'LoRaCmdCtrl';
USE LCC;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES, EXECUTE, CREATE ROUTINE, ALTER ROUTINE, TRIGGER ON `LCC`.* TO 'lccdbuser'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE commands (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `cmd_name` VARCHAR(255) DEFAULT NULL,
  `cmd_type` INT(11) DEFAULT NULL,
  `direction` TINYINT(4) DEFAULT NULL,
  `speed` TINYINT(4) DEFAULT NULL,
  `duration` INT(11) DEFAULT NULL,
  `progression` INT(11) DEFAULT NULL,
  `steps` INT(11) DEFAULT NULL,
  `location_id` INT(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `commands` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE devices (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(10) DEFAULT NULL,
  `dev_name` VARCHAR(255) DEFAULT NULL,
  `dev_type` INT(11) DEFAULT NULL,
  `last_loc` INT(11) DEFAULT NULL,
  `enabled` BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `devices` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE inbound (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(10) DEFAULT NULL,
  `msg` VARCHAR(255) DEFAULT NULL,
  `creation` timestamp NULL DEFAULT NULL,
  `rcvd` BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `inbound` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE locations (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `loc_name` VARCHAR(255) DEFAULT NULL,
  `pin` INT(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `locations` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE outbound (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(10) DEFAULT NULL,
  `msg` VARCHAR(255) DEFAULT NULL,
  `creation` timestamp NULL DEFAULT NULL,
  `sent` BOOLEAN DEFAULT FALSE,
  `acked` BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `outbound` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

COMMIT;
