DROP USER IF EXISTS 'lccdbuser'@'localhost';
DROP DATABASE IF EXISTS LCC;
CREATE DATABASE LCC;
CREATE USER 'lccdbuser'@'localhost' IDENTIFIED BY 'LoRaCmdCtrl';
USE LCC;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES, EXECUTE, CREATE ROUTINE, ALTER ROUTINE, TRIGGER ON `LCC`.* TO 'lccdbuser'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE commands (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `cmd_name` VARCHAR(255) DEFAULT NULL,
  `cmd_type` TINYINT(4) DEFAULT NULL,
  `cmd_class` TINYINT(4) DEFAULT NULL,
  `direction` TINYINT(4) DEFAULT NULL,
  `speed` TINYINT(4) DEFAULT NULL,
  `duration` INT(11) DEFAULT NULL,
  `progression` INT(11) DEFAULT NULL,
  `steps` INT(11) DEFAULT NULL,
  `resolution` TINYINT(4) DEFAULT NULL,
  `sound` INT(11) DEFAULT NULL,
  `replay` TINYINT(4) DEFAULT 0,
  `location_id` INT(11) DEFAULT NULL,
  `location_action` INT(11) DEFAULT NULL,
  `location_data` INT(11) DEFAULT NULL,
  `light` INT(11) DEFAULT 0,
  `red` INT(11) DEFAULT 0,
  `gren` INT(11) DEFAULT 0,
  `blue` INT(11) DEFAULT 0,
  `fade` FLOAT DEFAULT 1.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `commands` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE devices (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(5) DEFAULT NULL,
  `dev_name` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `dev_type` TINYINT(4) DEFAULT NULL,
  `last_loc` INT(11) DEFAULT 0,
  `favorites` TEXT DEFAULT NULL,
  `replay` TINYINT(4) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `devices` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE inbound (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(5) DEFAULT NULL,
  `msg` VARCHAR(255) DEFAULT NULL,
  `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `rcvd` TINYINT(4) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `inbound` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE locations (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `loc_name` VARCHAR(255) DEFAULT NULL,
  `pin` INT(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `locations` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE outbound (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(5) DEFAULT NULL,
  `msg` VARCHAR(255) DEFAULT NULL,
  `creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `sent_time` TIMESTAMP DEFAULT NULL,
  `ack_time` TIMESTAMP DEFAULT NULL,
  `exec_time` TIMESTAMP DEFAULT NULL,
  `sent` TINYINT(4) DEFAULT 0,
  `ack` TINYINT(4) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `outbound` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE schedule (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `address` VARCHAR(10) DEFAULT NULL,
  `task_name` VARCHAR(255) DEFAULT NULL,
  `start_hour` TINYINT(4) DEFAULT NULL,
  `start_min` TINYINT(4) DEFAULT NULL,
  `days` VARCHAR(13) DEFAULT NULL,
  `last_run` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `disabled` TINYINT(4) DEFAULT 0,
  `script` INT(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `schedule` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE scenes (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `scn_name` VARCHAR(255) DEFAULT NULL,
  `source` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `scenes` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE scripts (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `scr_name` VARCHAR(255) DEFAULT NULL,
  `cmd_class` TINYINT(4) DEFAULT NULL,
  `replay` TINYINT(4) DEFAULT 0,
  `replay_id` INT(11) DEFAULT 0,
  `commands` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `scripts` MODIFY `ID` INT(11) NOT NULL AUTO_INCREMENT;

COMMIT;
