#!/bin/bash

cd /usr/share/lcc

while [ true ]; do
  ScriptStart=$(date +%s)
  ./scheduler.php
  ScriptEnd=$(date +%s)
  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 60 ]; then
    Delay=$((60 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
done
