#!/bin/bash

cd /usr/share/lcc

sleep 0.5

while [ true ]; do
  ScriptStart=$(date +%s)
  ./logic-processor.php
  ScriptEnd=$(date +%s)
  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 2 ]; then
    Delay=$((2 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
done
